services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Abcd1234@
      MYSQL_DATABASE: books
      MYSQL_PASSWORD: Abcd1234@
    volumes:
      - ./mysql:/var/lib/mysql